[platformio]
extra_configs = environment.ini

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.partitions = partitions.csv
lib_deps = 
	bogde/HX711 @ ^0.7.5
	adafruit/RTClib@^2.1.4
board_build.filesystem = littlefs

build_flags =
    -D WIFI_SSID=\"${secrets.wifi_ssid}\"
    -D WIFI_PASS=\"${secrets.wifi_pass}\"
	-D API_URL=\"${secrets.apiURL}\"

